apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: avelys-prod
  namespace: argo-cd
spec:
  project: default
  revisionHistoryLimit: 10
  source:
    repoURL: git@github.com:avade-fr/avelys.git
    targetRevision: master
    path: deploy/helm/avelys
    helm:
      releaseName: avelys
      valueFiles:
        - ../environments/prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: avelys-prod
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    managedNamespaceMetadata:
      labels:
        app.kubernetes.io/part-of: avelys
        environment: production
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
