apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "avelys.fullname" . }}-web
  labels:
    {{- include "avelys.labels" . | nindent 4 }}
data:
  config.js: |
    window.__APP_CONFIG__ = {
      apiBaseUrl: {{ .Values.web.runtimeConfig.apiBaseUrl | quote }},
      oidcAuthority: {{ .Values.web.runtimeConfig.oidcAuthority | quote }},
      oidcClientId: {{ .Values.web.runtimeConfig.oidcClientId | quote }},
      oidcRedirectUri: {{ .Values.web.runtimeConfig.oidcRedirectUri | quote }},
      oidcPostLogoutRedirectUri: {{ .Values.web.runtimeConfig.oidcPostLogoutRedirectUri | quote }}
    };
{{- if .Values.api.enabled }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "avelys.fullname" . }}-api
  labels:
    {{- include "avelys.labels" . | nindent 4 }}
data:
  APP_ENV: {{ .Values.api.config.appEnv | quote }}
  LOG_LEVEL: {{ .Values.api.config.logLevel | quote }}
  CORS_ORIGINS: {{ .Values.api.config.corsOrigins | quote }}
  AUTH_ENABLED: {{ .Values.api.config.authEnabled | quote }}
  OIDC_ISSUER_URL: {{ .Values.api.config.oidcIssuerUrl | quote }}
  OIDC_JWKS_URL: {{ .Values.api.config.oidcJwksUrl | quote }}
  OIDC_AUDIENCE: {{ .Values.api.config.oidcAudience | quote }}
{{- end }}
