{{- if .Values.registryCredentials.enabled }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ required "registryCredentials.name is required when registry credentials are enabled" .Values.registryCredentials.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "avelys.labels" . | nindent 4 }}
  {{- with .Values.registryCredentials.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  destination:
    create: {{ .Values.registryCredentials.destination.create }}
    name: {{ .Values.registryCredentials.destination.name }}
    overwrite: {{ .Values.registryCredentials.destination.overwrite }}
    type: {{ .Values.registryCredentials.destination.type }}
  mount: {{ .Values.registryCredentials.mount }}
  path: {{ required "registryCredentials.path is required when registry credentials are enabled" .Values.registryCredentials.path }}
  type: {{ .Values.registryCredentials.type }}
{{- end }}

